### ISSUE TITLE
【sendmsg安装完成后使用报错】

### ISSUE THREAD

**Issue by gaoxuande** [wenchao-h/bkci-plugin-sendmsg#1]
蓝鲸版本：6.1.2
蓝盾版本：1.7.36
sendmsg版本：7.0.0
#报错信息
[Install plugin]
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.2', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 39, in <module>
    from pip._vendor import requests, six
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 23, in <module>
    from . import certs
  File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/certs.py", line 17, in <module>
    from certifi import where
  File "/usr/lib/python2.7/site-packages/certifi/__init__.py", line 1, in <module>
    from .core import contents, where
  File "/usr/lib/python2.7/site-packages/certifi/core.py", line 17
    def where() -> str:
                ^
SyntaxError: invalid syntax

![image](https://github.com/wenchao-h/bkci-plugin-sendmsg/assets/105274769/fcd0aec0-29b7-4ef6-9da5-d39792740d12)
有没有什么解决办法。不敢动ci机器的python环境特来求助

**Comment by arsenalpoll** [comment]
hello，解决了吗？
